# fly.toml app configuration file generated for actionpoints on 2026-07-26T21:03:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'actionpoints'
primary_region = 'lhr'
kill_signal = 'SIGTERM'
swap_size_mb = 512

[build]

[deploy]
  release_command = '/app/bin/migrate'

[env]
  ECTO_IPV6 = 'true'
  PHX_HOST = 'actionpoints.fly.dev'
  POOL_SIZE = '5'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
